import enum


class DatabaseItemType(enum.Enum):
    NONE = "None"
    DOCUMENTS = "Documents"
    REVISION_DOCUMENTS = "RevisionDocuments"
    INDEXES = "Indexes"
    IDENTITIES = "Identities"
    TOMBSTONES = "Tombstones"
    LEGACY_ATTACHMENTS = "LegacyAttachments"
    CONFLICTS = "Conflicts"
    COMPARE_EXCHANGE = "CompareExchange"
    LEGACY_DOCUMENT_DELETIONS = "LegacyDocumentDeletions"
    LEGACY_ATTACHMENT_DELETIONS = "LegacyAttachmentDeletions"
    DATABASE_RECORD = "DatabaseRecord"
    UNKNOWN = "Unknown"
    COUNTERS = "Counters"
    ATTACHMENTS = "Attachments"
    COUNTER_GROUPS = "CounterGroups"
    SUBSCRIPTIONS = "Subscriptions"
    COMPARE_EXCHANGE_TOMBSTONES = "CompareExchangeTombstones"
    TIME_SERIES = "TimeSeries"
    REPLICATION_HUB_CERTIFICATES = "ReplicationHubCertificates"
    TIME_SERIES_DELETED_RANGES = "TimeSeriesDeletedRanges"


class DatabaseRecordItemType(enum.Enum):
    NONE = "None"
    CONFLICT_SOLVER_CONFIG = "ConflictSolverConfig"
    SETTINGS = "Settings"
    REVISIONS = "Revisions"
    EXPIRATION = "Expiration"
    PERIODIC_BACKUPS = "PeriodicBackups"
    EXTERNAL_REPLICATIONS = "ExternalReplications"
    RAVEN_CONNECTION_STRINGS = "RavenConnectionStrings"
    SQL_CONNECTION_STRINGS = "SqlConnectionStrings"
    RAVEN_ETLS = "RavenEtls"
    SQL_ETLS = "SqlEtls"
    CLIENT = "Client"
    SORTERS = "Sorters"
    SINK_PULL_REPLICATIONS = "SinkPullReplications"
    HUB_PULL_REPLICATIONS = "HubPullReplications"
    TIME_SERIES = "TimeSeries"
    DOCUMENTS_COMPRESSION = "DocumentsCompression"
    ANALYZERS = "Analyzers"
    LOCK_MODE = "LockMode"
    OLAP_CONNECTION_STRINGS = "OlapConnectionStrings"
    OLAP_ETLS = "OlapEtls"
    ELASTIC_SEARCH_CONNECTION_STRINGS = "ElasticSearchConnectionStrings"
    ELASTIC_SEARCH_ETLS = "ElasticSearchEtls"
    POSTGRE_SQL_INTEGRATION = "PostgreSQLIntegration"
    QUEUE_CONNECTION_STRINGS = "QueueConnectionStrings"
    QUEUE_ETLS = "QueueEtls"
    INDEXES_HISTORY = "IndexesHistory"
    REFRESH = "Refresh"
    QUEUE_SINKS = "QueueSinks"
    DATA_ARCHIVAL = "DataArchival"
    SNOWFLAKE_CONNECTION_STRINGS = "SnowflakeConnectionStrings"
    SNOWFLAKE_ETLS = "SnowflakeEtls"
    EMBEDDINGS_GENERATIONS = "EmbeddingsGenerations"
    AI_CONNECTION_STRINGS = "AiConnectionStrings"
    GEN_AI_ETLS = "GenAiEtls"
    AI_AGENTS = "AiAgents"
    REMOTE_ATTACHMENTS = "RemoteAttachments"
    SCHEMA_VALIDATION = "SchemaValidation"


class ExportCompressionAlgorithm(enum.Enum):
    ZSTD = "Zstd"
    GZIP = "Gzip"
